### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by kielnino** [madalinabuzau/tensorflow-eager-tutorials#2]
Hi, 

thank you for this great tutorials. I like your style of putting the model and all its training-function in one class.

However I was not able to find a method to load one of the pretrained TF/Keras models in such class. Do you have an idea how to accomplish this?

Thanks!

**Comment by madalinabuzau** [comment]
Hi, 

Thank you a lot for your feedback. I am happy to see these tutorials are useful :).

Question [1]: If I understand correctly, you want to define a method in a class that is able to restore the trained weights of the model defined in that particular class. The CNN and LSTM tutorials have a method called 'restore_model' that is able to do so. Hope this helps :)!

**Comment by kielnino** [comment]
Hi, 
not exactly. I am used to use pretrained models like this:

``image_model = tf.keras.applications.InceptionV3(include_top=False, 
                                                weights='imagenet')``

where the model is loaded with weigths, pretrained on imagenet. 
But how do I use this `Inception` as a base-model and add my own layers like in your code.
