### ISSUE TITLE
how to restrict memory of gpu for tensorflow using？

### ISSUE THREAD

**Issue by Johnson-yue** [madalinabuzau/tensorflow-eager-tutorials#3]
Hi，Thanks your tutorials！ it is a great help to me. Yep, it is me again
But I have one question: How to restrict memory of GPU for tensorflow using?
I know  in static graph mode:
` gpu_option = tf.GPUOptions(allow_growth=True)`
`config = tf.ConfigProto(log_device_placement=False`
`                                       allow_soft_placement=True,`
`                                        gpu_options=gpu_option)`
`with tf.Session(config=config) as sess:`
`                # something you want to do`

But in eager mode, it have not sess  ,So, how to config tf?

**Comment by madalinabuzau** [comment]
Hi, you can pass the same config to tf.enable_eager_execution(config=config). It should work :).
[Here](https://www.tensorflow.org/api_docs/python/tf/enable_eager_execution) you can find more on how to configure the eager session  Hope this helps!

**Comment by Johnson-yue** [comment]
@madalinabuzau  thank you very much , I have found this function. you are so kind
